### ISSUE TITLE
command to toggle the bar

### ISSUE THREAD

**Issue by NicTanghe** [amnweb/yasb#153]
### What is the request?

    Just a quick display / hide with komoribi window pos adjustment.a

### Why is it useful?

I hate things that takeup space that it shouldn`t be taking up and autohide is inconsistant.

**Comment by amnweb** [comment]
Are you talking about CLI command?

**Comment by NicTanghe** [comment]
yes something to bind to a key.

**Comment by amnweb** [comment]
YASB does not support keybindings, but I can create a command to run an like `yasbc toggle-bar` and you can bind this command in WHKD or AutoHotkey.

**Comment by mooncakke** [comment]
Is there any way for the yasb status bar to auto hide instead of always being fixed on the Windows screen? This feature would be very useful for smaller screens.

**Comment by amnweb** [comment]
> Is there any way for the yasb status bar to auto hide instead of always being fixed on the Windows screen? This feature would be very useful for smaller screens.

Yeah, that's what I've been trying to make. There were a lot of problems, but I’ll finish it once I have more free time.

https://github.com/user-attachments/assets/af4043f1-91c5-4a9b-900f-0c9f93a70c8b

**Comment by NicTanghe** [comment]
yasbc toggle-bar whould be ideal yes !

**Comment by amnweb** [comment]
> yasbc toggle-bar whould be ideal yes ! ps(auto hide is wonky and never works like you want it to but if its both I`m all for it)

But what if you have multiple bars or multiple screens?
Should `toggle-bar` hide all bars on all screens?


@mooncakke two bars on same screen, on 2nd bar just taskbar widget.

**Comment by ericreeves** [comment]
I think ideally you, there would be a way to toggle all bars, and another option to target a specific bar on a specific screen.  Then folks could do whatever they wanted!

If you are looking for even more flexibility, commands to 'show-bar' and 'hide-bar' for all/specific bars could be useful too.

For example, if you're using a Streakdeck, you can setup a multi-action button that calls show/hide independently,  and then the Streamdeck button display could accurately reflect the current state.  (If the Streamdeck just calls "toggle" it can't know current state, and could easily get "out of sync").

**Comment by amnweb** [comment]
I have implemented show and hide commands via the CLI. YASB will continue to work in the background when it is hidden. Is an implementation like this acceptable?

https://github.com/user-attachments/assets/9313bb99-2050-41ec-bc02-eb775e37855d

**Comment by ProgrammerManSudjo** [comment]
This sounds awesome, because currently I've mapped via whkd (komorebi's hotkeys) the following "yasbc stop" and "yasbc start" commands to toggle the bars (which meant restarting the program multiple times on 2 monitors).

An AutoHide feature similar to the native Windows taskbar would be more intuitive but I reckon it would be much harder to implement. Where it reacts to a mouse over/hover, perhaps a hot corner could be better (just brainstorming some ideas).

**Comment by ericreeves** [comment]
So, if the bar is hidden, that space is still reserved and cannot be used by other applications.  It is simply not drawing the bar, correct?

If so, maybe stop/start is the behavior I actually wanted anyway.   My initial thought was that a hide/show command would be faster/more responsive than a full process stop/start...

Thanks so much either way!

**Comment by amnweb** [comment]
Yeah, we can just quickly hide the bar, but Windows will still use this space because YASB is running in bg

https://github.com/user-attachments/assets/56df745a-2bff-4106-a389-3113b6179e1d

**Comment by ericreeves** [comment]
I could still see some folks wanting to use this.  Folks with OLED displays that are paranoid about burn-in may care...

**Comment by anventia** [comment]
Would it be possible to toggle the `windows_app_bar` setting as well to get rid of the gap?

The autohide feature where it appears on top of the window like you showed a few messages up does look very useful!

For me personally, `start` and `stop` wouldn't work as I'd ideally like to have it permanent on one bar (on one monitor), but have another bar be on autohide mode and be toggleable.

**Comment by amnweb** [comment]
`windows_app_bar` must be set to false to work in both options auto-hide or via CLI. We cannot manipulate the Windows API in that way to register/unregister YASB as a status bar when you just want to hide the bar

**Comment by NanoLivs** [comment]
> > I could still see some folks wanting to use this. Folks with OLED displays that are paranoid about burn-in may care...
> 
> Why not just `yasbc start` and `yasbc stop` command ? I mean, YASB starts relatively fast, so I think it's not a big problem or am I missing the point?

Auto-hide and toggle (hotkey) options are important to at least three types of users:

1. OLED Monitor owners afraid of burn-in
2. Minimalists ("I want to see the bar only when I need it")
3. Users who want to maximize usable monitor space

**Comment by Video-Nomad** [comment]
> Any updates on this? Would like to try the bar, but not if auto-hide is not there(oled user)

Already in the pre-release: https://github.com/amnweb/yasb/releases/tag/dev
Commands are: `show-bar`, `hide-bar`, and `toggle-bar`
Example: `yasbc toggle-bar`

**Comment by ProgrammerManSudjo** [comment]
It looks really nice, 400ms is a sweet spot because it makes it feel more snappy and makes it feel more mouse over friendly (in case of accidental mouse movements).

Also is the `autohide` flag only mainly enabled from the config, or also it will be available for toggle via `yasbc`?

And thank you so much for the amazing project!

**Comment by anventia** [comment]
Looks great! 

I wonder if maybe a good delay would be the same delay as the Windows Taskbar autohide?

**Comment by anventia** [comment]
Just installed it!

Right now it doesn't seem to work all the time, when I have a maximized window open, it doesn't appear when I mouse at the top.
However, if I click at the very top of my screen, it appears instantly with no animation, then proceeds to work as expected until I click my maximized window again, focusing on it.

If I then alt-tab to a non-maximized window, it won't work until I click at the top again, and this brings the bar into focus (and not the maximized window underneath). I can then freely click around the floating window and the bar will keep auto-show/hiding as expected. It's only when I click a maximized window that it stops auto-hiding after initially clicking at the top.

**Comment by amnweb** [comment]
As you can see in this video, even if another window is active or focused, YASB still shows up when I move the mouse over it.

https://github.com/user-attachments/assets/e2e01cfe-4be0-486f-90c0-032d525aa2cc

**Comment by amnweb** [comment]
> [@amnweb](https://github.com/amnweb) so the auto hide works but when it hides i keeps the space reserved for it, so like komorebi for example won't take up the space where bar is supposed to be, even when bar is hidden, is it supposed to be like that?

That's normal. I can't unregister the bar on hide and then register it again, this is simply not how the Windows API works. You can check how the Taskbar behaves, it works the same way as YASB with auto-hide

Windows Taskbar (without auto-hide) == YASB `windows_app_bar: true`
Windows Taskbar (with auto-hide) == YASB `windows_app_bar: false` -> `auto_hide: true` -> always_on_top: true

**Comment by amnweb** [comment]
> > Do you have `always_on_top` enabled in the config? And which OS are you using?
> 
> Ah, I did not, enabling that fixed it! Thanks! (im on WIndows 11 24H2)
> 
> Right now it triggers when the mouse is slightly away from the top of the screen, would it be possible to reduce this distance to mitigate accidental activation?
> 

The trigger area/zone for bar activation is calculated automatically. For example, the default and minimum trigger area is 1px. But if you have a bar with a top padding of 10px, the trigger area becomes 1px + padding-top, which results in 11px.

**Comment by amnweb** [comment]
> Another thing I noticed, sometimes when alt-tabbing between two maximized windows, (and all the time when going from a fullscreen borderless game to a maximized window), the bar shows itself.

I need more information about the window flags from the config, and it would be best if you could show me in a video what the problem is.

**Comment by anventia** [comment]
> The trigger area/zone for bar activation is calculated automatically. For example, the default and minimum trigger area is 1px. But if you have a bar with a top padding of 10px, the trigger area becomes 1px + padding-top, which results in 11px.

Oh, i see :/

> I need more information about the window flags from the config, and it would be best if you could show me in a video what the problem is.

Tried disabling hide on fullscreen and the issue went away!

**Comment by AtifChy** [comment]
@amnweb is there a way to autohide the bar when a window is maximized?

**Comment by amnweb** [comment]
> [@amnweb](https://github.com/amnweb) is there a way to autohide the bar when a window is maximized?

Not currently, but this feature may be added in a future release

**Comment by Mhjulstad** [comment]
@amnweb is there a way to hide, auto-hide, or disable always_on_top for the yasb bar for a specific komorebi workspace or when a window is maximized? Would be nice to just have a dedicated workspace for games. Or is there another better solution already available? 

<img width="2559" height="1599" alt="Image" src="https://github.com/user-attachments/assets/80ac50ce-a36e-41ee-9f72-831d80a26a15" />

**Comment by amnweb** [comment]
> [@amnweb](https://github.com/amnweb) is there a way to hide, auto-hide, or disable always_on_top for the yasb bar for a specific komorebi workspace or when a window is maximized? Would be nice to just have a dedicated workspace for games. Or is there another better solution already available?
> <img alt="Image" width="2000" height="1599" src="https://private-user-images.githubusercontent.com/141959307/466721818-80ac50ce-a36e-41ee-9f72-831d80a26a15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI2MTkyMDIsIm5iZiI6MTc1MjYxODkwMiwicGF0aCI6Ii8xNDE5NTkzMDcvNDY2NzIxODE4LTgwYWM1MGNlLWEzNmUtNDFlZS05ZjcyLTgzMWQ4MGEyNmExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxNVQyMjM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmY3YWMwNWJmZGU3MjAwOGFiMTQzZmYyMTQxOWRmMjY2YjAxZWZkZThhMDFjMjAyMTcwYTZhYWU2ZmRlYTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mp5F6L3CouoDLxHIIQth7VmV2vc0RzWMNqokwS8vhDk">

Auto hide should work fine with fullscreen but not for maximized window. This is not yet implemented. You can hide the bar with the command line. If you use `whkd`, you can set up a keybind for the command. You can also right-click on the bar to enable or disable autohide when needed. However, this feature cannot be controlled on a per-workspace basis

**Comment by Mhjulstad** [comment]
Yeah, I ended up changing primary bar to `always_on_top`, then binding `toggle-bar` in whkdrc to toggle on/off when launching games etc. 

Side note: Also sent a PR to komorebi to display other shortcuts than just komorebic when pressing `alt + i` as LGUG2Z wanted that change anyways

**Comment by amnweb** [comment]
> Side note: Also sent a PR to komorebi to display other shortcuts than just komorebic when pressing `alt + i` as LGUG2Z wanted that change anyways

You have a widget for that
https://github.com/amnweb/yasb/wiki/(Widget)-Whkd

<img width="900" height="901" alt="Image" src="https://github.com/user-attachments/assets/ce7acbfa-df14-4869-bb74-55b57b428b1c" />

**Comment by Mhjulstad** [comment]
Nice! Guess he just wanted to tidy up the default one a little
